server.port=1994

spring.application.name=config
spring.cloud.config.server.git.uri=https://github.com/SiriusCM/config.git
spring.cloud.config.server.git.search-paths=config
#git的用户名
spring.cloud.config.server.git.username=963937371@qq.com
#git的密码
spring.cloud.config.server.git.password=mogu1128

management.endpoint.shutdown.enabled=true