server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://10.4.4.208:10000/eureka

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: config